on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          target: builder
          tags: vregazzi/todo-frontend:test

      - name: Test
        run: |
          docker run --rm vregazzi/todo-frontend:test npm run test
